version: '3.8'

services:
  backend:
    image: sjc.vultrcr.com/reelratings/reelratings-backend:latest
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TZ=/etc/localtime
    volumes:
      - /etc/localtime:/etc/localtime:ro

  frontend:
    image: sjc.vultrcr.com/reelratings/reelratings-frontend:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - TZ=/etc/localtime
    volumes:
      - /etc/localtime:/etc/localtime:ro

networks:
  default:
    name: reelratings_network
