version: '3.8'

services:
  backend:
    image: https://sjc.vultrcr.com/reelratings/reelratingsdb-backend:${APP_VERSION:-latest}
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    image: https://sjc.vultrcr.com/reelratings/reelratingsdb-frontend:${APP_VERSION:-latest}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend